name: Output info
on: 
  - issues
  - workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show event name
        run: echo "Event name: ${{ github.event_name }}"
      - name: Dump full event payload:
        run: echo "${{ toJson(github.event) }}"
