name: Output info
on: 
  - issues
  - workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: echo "Event name: $EVENT_NAME"
      - name: Dump full event payload:
        run: echo "${{ toJson(github.event) }}"
